# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: development

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11" # The JDK version to make available on the path.
      - name: Build with Maven
        run: mvn test
      # - name: Upload Application Artifact
      # uses: actions/upload-artifact@v2
      # with:
      # name: Application
      # path: shade/Application.jar
      # - name: Upload Application Artifact
      # uses: actions/upload-artifact@v2
      # with:
      # name: Server
      # path: shade/Server.jar*/
      - name: Upload Coverage Reports
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Commit Javadoc
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/apidocs
          git commit -m "Update Javadoc"
      - name: Update Javadoc
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
