# This workflow will upload codecoverage in Codecov

name: master_status_update

on:
  push:
    branch: [master]
  pull_request:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Maven Test
        run: mvn test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/site/jacoco/jacoco.xml
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Commit Javadoc & Jacoco Coverage
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/apidocs
          git commit -m "Update Javadoc"
          mv target/site/jacoco/ docs/
          git add docs/jacoco
          git commit -m "Update Jacoco Coverage"
      - name: Update Javadoc & Jacoco Coverage
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
